# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/acoshift/configfile"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/acoshift/csrf"

[[constraint]]
  branch = "master"
  name = "github.com/acoshift/header"

[[constraint]]
  name = "github.com/acoshift/hime"
  version = "0.0.15"

[[constraint]]
  name = "github.com/acoshift/httprouter"
  version = "2.1.0"

[[constraint]]
  name = "github.com/acoshift/middleware"
  version = "0.2.0"

[[constraint]]
  name = "github.com/acoshift/session"
  version = "0.6.0"

[[constraint]]
  name = "github.com/acoshift/webstatic"
  version = "1.0.0"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[prune]
  go-tests = true
  unused-packages = true
