[[constraint]]
  branch = "master"
  name = "github.com/acoshift/configfile"

[[constraint]]
  branch = "master"
  name = "github.com/acoshift/header"

[[constraint]]
  branch = "master"
  name = "github.com/acoshift/hime"

[[constraint]]
  name = "github.com/acoshift/httprouter"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/acoshift/middleware"

[[constraint]]
  branch = "master"
  name = "github.com/acoshift/session"

[[constraint]]
  branch = "master"
  name = "github.com/acoshift/webstatic"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
