[[constraint]]
  name = "github.com/acoshift/configfile"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/acoshift/header"

[[constraint]]
  name = "github.com/acoshift/hime"
  version = "0.7.4"

[[constraint]]
  name = "github.com/acoshift/httprouter"
  version = "2.1.0"

[[constraint]]
  name = "github.com/acoshift/middleware"
  version = "0.4.1"

[[constraint]]
  name = "github.com/acoshift/session"
  version = "0.9.0"

[[constraint]]
  name = "github.com/acoshift/webstatic"
  version = "2.0.0"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
